from tkinter import * 
window=Tk() 
window.title("1. STUDENT")
l1=Label(window,text="Regno : ").grid(row=0,column=0) 
t1=Entry(window).grid(row=0,column=1) 
l2=Label(window,text="Name : ").grid(row=1,column=0) 
t2=Entry(window).grid(row=1,column=1) 
l3=Label(window,text="Dept : ").grid(row=2,column=0) 
t3=Entry(window).grid(row=2,column=1) 
l4=Label(window,text="Gender : ").grid(row=3,column=0) 
r1=Radiobutton(window,text="Male",value=1).grid(row=3, column=1) 
r2=Radiobutton(window,text="Female",value=2).grid(row=3, column=2) 
l5=Label(window,text="Age : ").grid(row=4,column=0) 
sb=Spinbox(window,from_=0, to=25).grid(row=4,column=1) 
b1=Button(window,text="Insert").grid(row=5,column=0) 
b2=Button(window,text="Update").grid(row=5,column=2) 
b3=Button(window,text="Delete").grid(row=6,column=0) 
b4=Button(window,text="Select").grid(row=6,column=2) 
window.mainloop()
