from tkinter import*
import tkinter.ttk as ttk 
window=Tk() 
window.title('10. Phone List') 
window.configure(bg="grey")
l1=Label(window,text="Name",bg='Grey').grid(row=0,column=0) 
e1=Entry(window).grid(row=0,column=1) 
l2=Label(window,text="Phone",bg='Grey').grid(row=1,column=0) 
e2=Entry(window).grid(row=1,column=1) 
le=Label(window,bg="grey").grid(row=2,column=0) 
b1=Button(window,text="Add",bg='light grey').grid(row=3,column=0) 
b2=Button(window,text="Update",bg='light grey').grid(row=3,column=1) 
b3=Button(window,text="Delete",bg='light grey').grid(row=3,column=2) 
le=Label(window,bg="grey").grid(row=4,column=0)
s = ttk.Style() 
s.theme_use('clam')
s.configure('Treeview.Heading', background="light grey") 
tree =ttk.Treeview(window, column=("c1", "c2"),show='headings',height=5) 
tree.grid(row=5,column=1) 
tree.heading("# 1", text= "Name") 
tree.heading("# 2", text= "Phone")
tree.insert('', 'end',text= "1",values=('Barnhart,Ralph','683-2341')) 
tree.insert('', 'end',text="2",values=('Jones,Janet','483-5432')) 
tree.insert('', 'end',text= "3",values=('Meyers,Chris','343-4349'))
tree.insert('', 'end',text= "4",values=('Nelson,Eric','485-2689')) 
tree.insert('', 'end',text="5",values=('Prefect,Ford','987-6543')) 
tree.insert('', 'end',text= "6",values=('Smith,Bob','689-1234')) 
tree.insert('', 'end',text= "7",values=('Smith,Robert','689-1234')) 
window.mainloop()