from tkinter import *
import tkinter.ttk as ttk
window=Tk()
window.title('11. Billing Details') 
l1=Label(window,text="Name:").grid(row=0,column=0) 
e1=Entry(window).grid(row=0,column=1) 
le=Label(window).grid(row=1,column=0) 
l2=Label(window,text='Products:').grid(row=2,column=0) 
s = ttk.Style()
s.theme_use('clam')
s.configure('Treeview.Heading', background="light grey") 
tree=ttk.Treeview(window, column=("c1", "c2"), show= 'headings', height=4) 
tree.grid(row=2,column=1) 
tree.heading("# 1", text= "Items") 
tree.heading("# 2", text= "Price")
tree.insert('', 'end',text= "1",values=('Pen','10/-')) 
tree.insert('','end',text= "2",values=('Pencil','5/-')) 
tree.insert('', 'end',text= "3",values=('Eraser','10/-'))
tree.insert('', 'end',text= "4",values=('Sharpner','15/-')) 
le=Label(window).grid(row=3,column=0) 
l3=Label(window,text='Quantity:').grid(row=4,column=0) 
e2=Entry(window).grid(row=4,column=1) 
le=Label(window).grid(row=5,column=0) 
b1=Button(window,text='Add Items').grid(row=6,column=1) 
e3=Text(window, height=10, width=40) 
le=Label(window).grid(row=7,column=0) 
e3.grid(row=8,column=1) 
le=Label(window).grid(row=9,column=0) 
b2=Button(window,text='Clear Items').grid(row=10,column=0) 
b3=Button(window,text='Total').grid(row=10,column=1) 
window.mainloop()
