from	tkinter	import	* 
window=Tk() 
window.title('3.EMPLOYEE')
a=IntVar()
l1=Label(window,text='Employee ID : ').grid(row=0,column=0) 
e1=Entry(window).grid(row=0,column=1) 
l2=Label(window,text='Employee Name : ').grid(row=1,column=0) 
e2=Entry(window).grid(row=1,column=1) 
l3=Label(window,text='Job : ').grid(row=2,column=0) 
e3=Entry(window).grid(row=2,column=1) 
l4=Label(window,text='Employee type : ').grid(row=3,column=0)
r1=Radiobutton(window,text='Regular',variable=a,value=0).grid(row=3,column=1) 
r2=Radiobutton(window,text='Temporary',variable=a,value=1).grid(row=3,column=2) 
l5=Label(window,text='Salary : ').grid(row=4,column=0) 
sb=Spinbox(window,from_=0, to=100000).grid(row=4,column=1) 
b1=Button(window,text="Insert").grid(row=5,column=0) 
b2=Button(window,text="Update").grid(row=5,column=2) 
b3=Button(window,text="Delete").grid(row=6,column=0) 
b4=Button(window,text="Select").grid(row=6,column=2) 
window.mainloop()
