from tkinter import * 
window=Tk() #CheckVar1=IntVar() #CheckVar2=IntVar()
window.title('5. MOVIE TICKET BOOKING') 
l1=Label(window,text='Movie Booking ID : ').grid(row=0,column=0) 
e1=Entry(window).grid(row=0,column=1) 
l2=Label(window,text='Person Name : ').grid(row=1,column=0) 
e2=Entry(window).grid(row=1,column=1) 
l3=Label(window,text='Movie Name : ').grid(row=2,column=0)
e3=Entry(window).grid(row=2,column=1) 
l4=Label(window,text="Class : ").grid(row=3,column=0) 
r1=Radiobutton(window,text='A',value=0).grid(row=3,column=1)
r2=Radiobutton(window,text='B',value=1).grid(row=3,column=2) 
l5=Label(window,text='Time of Show : ').grid(row=3,column=3) 
chkb1=Checkbutton(window,text="7:15pm",onvalue=1,offvalue=0).grid(row=3,column=4) 
chkb2=Checkbutton(window,text="9:00am",onvalue=1,offvalue=0).grid(row=3,column=5)
l6=Label(window,text="No. of Tickets").grid(row=4,column=0) 
scale=Scale(window,from_=1,to=5,orient=HORIZONTAL).grid(row=4,column=1) 
b1=Button(window,text="Insert").grid(row=5,column=0) 
b2=Button(window,text="Update").grid(row=5,column=2) 
b3=Button(window,text="Delete").grid(row=6,column=0) 
b4=Button(window,text="Select").grid(row=6,column=2) 
#b5=Button(window,text="Quit",command=window.destroy).grid(row=7,column=1) 
window.mainloop()
