from tkinter import * 
window=Tk()
window.title("6. Customer Loan Details") 
l1=Label(window,text="Annual Rate : ").grid(row=0,column=0) 
e1=Entry(window).grid(row=0,column=1) 
l2=Label(window,text="Number of Payments : ").grid(row=1,column=0) 
e2=Entry(window).grid(row=1,column=1)
l3=Label(window,text="Loan Principle : ").grid(row=2,column=0) 
e3=Entry(window).grid(row=2,column=1) 
l4=Label(window,text="Monthly Payment : ").grid(row=3,column=0) 
e4=Entry(window).grid(row=3,column=1) 
l5=Label(window,text="Remaining Loan : ").grid(row=4,column=0) 
e5=Entry(window).grid(row=4,column=1)
b1=Button(window,text="Final Balance").grid(row=5,column=0) 
b2=Button(window,text="Monthly Payment").grid(row=5,column=1)
b3=Button(window,text="Quit",command=window.destroy).grid(row=5,column=2) 
window.mainloop()