from tkinter import* 
window=Tk()
window.title('7. Contact Details') 
l1=Label(window,text="Contact List").grid(row=0,column=1) 
lstbx1=Listbox(window).grid(row=1,column=1)
b1=Button(window,text="Display Contact").grid(row=2,column=1) 
le=Label(window,text="").grid(row=3,column=0) 
l2=Label(window,text='Last Name :').grid(row=4,column=0) 
e1=Entry(window).grid(row=4,column=1) 
b2=Button(window,text="Search").grid(row=6,column=1) 
le=Label(window,text="").grid(row=6,column=1) 
l3=Label(window,text="New Contact").grid(row=0,column=4) 
l4=Label(window,text="First Name:").grid(row=1,column=5) 
e2=Entry(window).grid(row=1,column=6) 
l5=Label(window,text="Last Name:").grid(row=2,column=5) 
e3=Entry(window).grid(row=2,column=6) 
l6=Label(window,text="Phone #:").grid(row=3,column=5) 
e4=Entry(window).grid(row=3,column=6)
CheckVar=IntVar()
chkb=Checkbutton(window,text="Friend",onvalue=1,offvalue=0).grid(row=4,column=6)
l7=Label(window,text="Email:").grid(row=5,column=5) 
e5=Entry(window).grid(row=5,column=6) 
l8=Label(window,text="Birthday:").grid(row=6,column=5) 
e6=Entry(window).grid(row=6,column=6) 
b3=Button(window,text="Add Contact").grid(row=7,column=6)
window.mainloop()
