from tkinter import * 
window=Tk()
window.title('8. Registration Form') 
window.configure(bg='light green') 
l1=Label(window,text="Form",bg='light green').grid(row=0,column=1) 
l2=Label(window,text="Name",bg='light green').grid(row=1,column=0) 
e1=Entry(window,width=50).grid(row=1,column=1)
l3=Label(window,text="Course",bg='light green').grid(row=2,column=0) 
e2=Entry(window,width=50).grid(row=2,column=1) 
l4=Label(window,text="Semester",bg='light green').grid(row=3,column=0) 
e3=Entry(window,width=50).grid(row=3,column=1) 
l5=Label(window,text="Form No.",bg='light green').grid(row=4,column=0) 
e4=Entry(window,width=50).grid(row=4,column=1) 
l6=Label(window,text="Contact No.",bg='light green').grid(row=5,column=0) 
e5=Entry(window,width=50).grid(row=5,column=1) 
l7=Label(window,text="Email id",bg='light green').grid(row=6,column=0) 
e6=Entry(window,width=50).grid(row=6,column=1) 
l8=Label(window,text="Address",bg='light green').grid(row=7,column=0) 
e7=Entry(window,width=50).grid(row=7,column=1) 
b1=Button(window,text="Submit",bg='red').grid(row=8,column=1) 
window.mainloop()